apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dummy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: memoliyasti/dummy-spring-boot:blue 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        